# Generated by Django 5.0.4 on 2024-04-21 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=70)),
                ('cus_email', models.EmailField(max_length=254, unique=True)),
                ('cus_phone_no', models.CharField(max_length=12)),
                ('cus_add', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_type', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=15)),
                ('submit_at', models.DateTimeField(auto_now_add=True)),
                ('solved_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_requests.customer')),
            ],
        ),
    ]
